"""Generates the three tables of chapter 4 as LaTeX fragments.

Why this exists: there was no link at all between the simulation code and the
tables in the text. All three sat as empty `\\fbox` placeholders with the note
"fill in once the last 19 runs are in", and the intention was to type them over
by hand from a working document. That is exactly where numbers drift apart from
the data they come from.

Each fragment gets a comment line at the top with the commit, the date and the
runset count, so a table can never come loose from its origin.

    python3 make_tables.py            # writes to tables/
    python3 make_tables.py --stdout   # shows without writing
"""
from __future__ import annotations

import subprocess
import sys
from datetime import date
from pathlib import Path

for _fam in ("_shared", "economy", "structure"):
    sys.path.insert(0, str(Path(__file__).resolve().parent / _fam))

import json

import runset
from grid_profile import compute as grid
from M31_channel_off import compute as kanaal

FIGUREN = Path(__file__).resolve().parent / "out" / "figures.json"


def figuur(label: str) -> dict:
    """A figure from the registry, so a table cannot disagree with the text.

    Table 2 used to come from `structure/M39_form_profile.py`, a second
    implementation of the same four forms with different definitions behind
    three of them --- it counted mutual strengthening as a reciprocal pair,
    required a repeated edge before a cycle counted, and detected accusations by
    proximity, which is the reading the appendix records as correct in roughly
    six cases of thirty. The table and the chapter therefore printed different
    numbers for the same quantities. It now reads what the chapter reads.
    """
    d = json.loads(FIGUREN.read_text())["figures"]
    if label not in d:
        raise SystemExit(f"{label} is not in out/figures.json — run registry.py first")
    return d[label]["result"]

UIT = Path(__file__).resolve().parent / "tables"
LABELS = {"scar": "scarce", "knife": "knife-edge", "abund": "abundant"}


def _commit() -> str:
    try:
        return subprocess.run(["git", "rev-parse", "--short", "HEAD"],
                              capture_output=True, text=True,
                              cwd=Path(__file__).parent).stdout.strip() or "unknown"
    except OSError:
        return "unknown"


def _kop(wat: str, n: int) -> str:
    return (f"% {wat}\n"
            f"% Generated by measures/make_tables.py on {date.today()}\n"
            f"% Commit {_commit()} · runset data/thesis_final/ · {n} runs\n"
            f"% Do not edit by hand — re-run the script instead.\n")


# Each rung adds one action and never removes one, so an action that is not yet
# in a rung's schema has no rate at all. Printing 0.0 there says the agents
# chose not to do it; they could not. A dash says so, and Table 3 leaves the row
# out entirely, since it has one row per measure and can afford to.
SCHEMA = {"L1": {"hold", "transfer"},
          "L2": {"hold", "transfer", "take", "strengthen"},
          "L3": {"hold", "transfer", "take", "strengthen", "rewire"},
          "L4": {"hold", "transfer", "take", "strengthen", "rewire", "harvest"}}


def _cel(waarde, actie, rung):
    return f"{waarde:.1f}" if actie in SCHEMA[rung] else "---"


def tabel_grid() -> str:
    g = grid()
    # Ten columns fit within the text block only when shrunk, hence \footnotesize.
    r = [_kop("Table 1 — action shares and final Gini per cell", sum(v["n"] for v in g.values())),
         r"\footnotesize",
         r"\begin{tabular}{llrrrrrrrr}", r"\toprule",
         r"level & payoff & $n$ & Gini (M$\pm$SD) & hold & transfer & take & "
         r"streng. & harvest & rewire \\", r"\midrule"]
    for rung in ("L1", "L2", "L3", "L4"):
        for payoff in ("scar", "knife", "abund"):
            c = g[f"prod_{rung}_{payoff}"]; a = c["acties"]
            r.append(f"{rung} & {LABELS[payoff]} & {c['n']} & "
                     f"{c['gini_mean']:.3f}$\\pm${c['gini_sd']:.3f} & "
                     f"{_cel(a['hold'], 'hold', rung)} & "
                     f"{_cel(a['transfer'], 'transfer', rung)} & "
                     f"{_cel(a['take'], 'take', rung)} & "
                     f"{_cel(a['strengthen'], 'strengthen', rung)} & "
                     f"{_cel(a['harvest'], 'harvest', rung)} & "
                     f"{_cel(c['rewire']['rewire'], 'rewire', rung)} \\\\")
        r.append(r"\addlinespace")
    r.append(r"\midrule")
    for naam, etiket in ([(f"prod_{x}_knife_nocomm", f"{x} no-channel") for x in
                          ("L1", "L2", "L3", "L4")] +
                         [(f"robust_qwen_{x}_knife", f"{x} Qwen") for x in ("L2", "L3", "L4")]):
        c = g[naam]; a = c["acties"]
        r.append(f"\\multicolumn{{2}}{{l}}{{{etiket}}} & {c['n']} & "
                 f"{c['gini_mean']:.3f}$\\pm${c['gini_sd']:.3f} & "
                 f"{a['hold']:.1f} & {a['transfer']:.1f} & {a['take']:.1f} & "
                 f"{a['strengthen']:.1f} & {a['harvest']:.1f} & "
                 f"{c['rewire']['rewire']:.1f} \\\\")
    r += [r"\bottomrule", r"\end{tabular}"]
    return "\n".join(r) + "\n"


def tabel_forms() -> str:
    v = figuur("m:form-profile")
    sanctie = figuur("m:accusation-collective-sanction")
    cellen = [f"prod_{r}_{p}" for r in ("L1", "L2", "L3", "L4")
              for p in ("scar", "knife", "abund")]
    r = [_kop("Table 2 — four arrangements per cell",
              sum(v[c]["n"] for c in cellen)),
         r"\begin{tabular}{llrrrrrr}", r"\toprule",
         r"level & payoff & $n$ & dyads & cycles & named & sanction & (chance) \\",
         r"\midrule"]
    for rung in ("L1", "L2", "L3", "L4"):
        for payoff in ("scar", "knife", "abund"):
            naam = f"prod_{rung}_{payoff}"
            c = v[naam]["value"]
            s_ = sanctie.get(naam)
            # Three states, not two: the level cannot sanction (no attack in its
            # schema), the detector found no accusation to follow, or a rate.
            if not s_:
                kol = kans = "---"
            elif not s_["value"].get("accusations"):
                kol, kans = "no acc.", "---"
            else:
                # One attacker or more, not two. At L2 a sanction can be
                # carried out by a single agent whom others have armed for it,
                # and requiring a crowd would count that as no sanction at all.
                kol = f"{s_['value']['followed_by_any_attack_pct']:.0f}\\%"
                kans = f"{s_['baseline']['any_attack_pct']:.0f}\\%"
            r.append(f"{rung} & {LABELS[payoff]} & {v[naam]['n']} & "
                     f"{c['reciprocal_pairs']['mean']:.1f} & "
                     f"{c['giving_cycles']['mean']:.1f} & "
                     f"{c['coined_names']['mean']:.1f} & {kol} & {kans} \\\\")
        r.append(r"\addlinespace")
    r += [r"\bottomrule", r"\end{tabular}"]
    return "\n".join(r) + "\n"


def tabel_channel() -> str:
    k = kanaal()
    n = sum(x["met"]["n"] + x["zonder"]["n"] for x in k.values())
    r = [_kop("Table 3 — each control cell against its speaking counterpart", n),
         r"\begin{tabular}{llrr}", r"\toprule",
         r"level & measure & with channel & without \\", r"\midrule"]
    # "named forms per run" is not reported here. A coined name requires agents
    # to address one another, so the silent column is zero by construction and
    # the row compares a measurement against a definition.
    maten = [("transfer (\\% of turns)", "transfer"), ("take (\\% of turns)", "take"),
             ("harvest (\\% of turns)", "harvest")]
    for trede, x in k.items():
        a, b = x["met"], x["zonder"]
        r.append(f"\\multicolumn{{4}}{{l}}{{\\emph{{{trede} knife-edge, "
                 f"$n={a['n']}$ vs.\\ ${b['n']}$}}}} \\\\")
        for etiket, sleutel in maten:
            if sleutel in ("take", "harvest") and sleutel not in SCHEMA[trede]:
                continue
            va, vb = a[sleutel], b[sleutel]
            # bold = the side where the measure collapses, as the caption promises
            fa = f"\\textbf{{{va}}}" if vb and va < vb * 0.5 else f"{va}"
            fb = f"\\textbf{{{vb}}}" if va and vb < va * 0.5 else f"{vb}"
            r.append(f" & {etiket} & {fa} & {fb} \\\\")
        r.append(f" & mutual pairs per run & {a['paren'][0]} & {b['paren'][0]} \\\\")
        r.append(f" & mean final holding & {a['bezit'][0]} & {b['bezit'][0]} \\\\")
        r.append(r"\addlinespace")
    r += [r"\bottomrule", r"\end{tabular}"]
    return "\n".join(r) + "\n"


if __name__ == "__main__":
    try:
        tabellen = {"tab_grid.tex": tabel_grid(), "tab_forms.tex": tabel_forms(),
                    "tab_channel.tex": tabel_channel()}
    except runset.RunsetError as e:
        sys.exit(f"RUNSET: {e}")
    if "--stdout" in sys.argv:
        for naam, inhoud in tabellen.items():
            print(f"\n{'='*60}\n{naam}\n{'='*60}\n{inhoud}")
    else:
        UIT.mkdir(exist_ok=True)
        for naam, inhoud in tabellen.items():
            (UIT / naam).write_text(inhoud)
            print(f"  {UIT.name}/{naam}  ({len(inhoud.splitlines())} lines)")
