"""Supplementary: niveaus in de oorspronkelijke eenheid (AAMAS, 29 sep 2026).
(1) Mediaan [IQR] per trede, gepoold over de prijs, voor de 14 geregistreerde maten.
(2) Ablaties: mediaan per groep en Hodges--Lehmann-verschuiving (mediaan van alle paarsgewijze
    verschillen), met exacte permutatie-p voor Mann--Whitney bij n = 5. Leest de caches.
"""
import json, sys, re, itertools
from pathlib import Path
import numpy as np
HIER = Path(__file__).resolve().parent; M = HIER.parent
for s in ("core", "_shared"): sys.path.insert(0, str(M / s))
import runset
from _paths import PAPER
OUT = PAPER / "supplementary"
RUNGS = ("L1","L2","L3","L4"); PAYS = ("scar","knife","abund")
reg = json.loads((HIER / "prereg_fingerprint.json").read_text())
rows = {tuple(k.split("|")): v for k, v in json.loads((HIER / "prereg_per_run.json").read_text()).items()}
C = json.loads((HIER / "ablation_per_run.json").read_text())
seed = lambda p: re.search(r"__s(\d+)", p.name).group(1)
fmt = lambda x: f"{x:.3g}"

L = [r"% Supplementary table S1 --- generated by paper_aamas/supplementary_tables.py",
     r"\begin{tabular}{l" + "c"*4 + "}", r"\toprule", "measure & L1 & L2 & L3 & L4 \\\\", r"\midrule"]
for u in reg:
    cells = []
    for r in RUNGS:
        if r not in u["rungs"]: cells.append("---"); continue
        x = np.asarray([v[u["key"]] for p in PAYS for v in rows[(r, p)]], float)
        cells.append(f"{fmt(np.median(x))} [{fmt(np.percentile(x,25))}, {fmt(np.percentile(x,75))}]")
    L.append(f"{u['label'].replace('%', r'\%')} & " + " & ".join(cells) + " \\\\")
L += [r"\bottomrule", r"\end{tabular}"]
(OUT / "tab_levels.tex").write_text("\n".join(L) + "\n")

def hl(a, b): return float(np.median([y - x for x in a for y in b]))
def perm_p(a, b):
    a, b = list(a), list(b); allv = a + b; n = len(a)
    def u(x, y): return sum((yi > xi) - (yi < xi) for xi in x for yi in y)
    obs = abs(u(a, b)); cnt = tot = 0
    for idx in itertools.combinations(range(len(allv)), n):
        xa = [allv[i] for i in idx]; xb = [allv[i] for i in range(len(allv)) if i not in idx]
        tot += 1; cnt += abs(u(xa, xb)) >= obs
    return cnt / tot
abl = json.loads((HIER / "ablations.json").read_text())
T = [r"% Supplementary table S2 --- generated by paper_aamas/supplementary_tables.py",
     r"\begin{longtable}{llcccc}", r"\toprule", r"removal & measure & level & median before / after & HL shift & perm.\ $p$ \\", r"\midrule", r"\endhead"]
for name in ("model", "channel"):
    for k, v in abl[name].items():
        for r in ("L1","L2","L3","L4"):
            if r not in v: continue
            if name == "channel":
                alt = runset.cel(f"prod_{r}_knife_nocomm"); base = runset.cel(f"prod_{r}_knife")
            else:
                alt = runset.cel(f"robust_qwen_{r}_knife"); ss = {seed(p) for p in alt}
                base = [p for p in runset.cel(f"prod_{r}_knife") if seed(p) in ss]
            a = [C[p.name][k] for p in base]; b = [C[p.name][k] for p in alt]
            p = perm_p(a, b) if len(a) + len(b) <= 20 else float("nan")
            ptxt = ("$<.001$" if p < .0005 else f"{p:.3f}") if p == p else "---"
            T.append(f"{name} & {v['label'].replace('%', r'\%')} & {r} & {fmt(np.median(a))} / {fmt(np.median(b))} & {fmt(hl(a, b))} & {ptxt} \\\\")
T += [r"\bottomrule", r"\end{longtable}"]
(OUT / "tab_ablations.tex").write_text("\n".join(T) + "\n")
print("S1 en S2 geschreven naar", OUT)
