"""Twee tabellen voor de hoofdtekst (AAMAS, 7 okt 2026). Leest alleen opgeslagen uitkomsten; rekent niets opnieuw.

Tabel 2 (per level, Gemma, alle prijzen): arms_levels.json, modularity_null.json, reachable_baseline.json,
mob_per_reach.json, herreken.json (runs met een benoemde afspraak), channel_use.json, prereg_per_run.json.
Tabel 3 (armen, knife-edge): arms_levels.json.
  python3 paper_aamas/tables_main.py <map van het Overleaf-project>/sections
"""
import sys, json, statistics as st
from decimal import Decimal, ROUND_HALF_UP
from pathlib import Path
H = Path(__file__).resolve().parent
J = lambda n: json.loads((H / f"{n}.json").read_text())
al, mn, rb, mp, hr, cu = J("arms_levels"), J("modularity_null"), J("reachable_baseline"), J("mob_per_reach"), J("herreken"), J("channel_use")
pr = {tuple(k.split("|")): v for k, v in J("prereg_per_run").items()}
L4 = ("L1", "L2", "L3", "L4"); PAYS = ("scar", "knife", "abund")
D = "---"
def med(L, key): return st.median([r[key] for c in PAYS for r in pr[(L, c)]])
def pct(x): return D if x is None else f"{100 * x:.0f}"
def f2(x): return D if x is None else f"{x:.2f}".lstrip("0") if 0 <= x < 1 else f"{x:.2f}"
def f1(x): return D if x is None else str(Decimal(str(x)).quantize(Decimal("0.1"), ROUND_HALF_UP))

lv = al["levels"]
names_any = {L: st.mean(hr["names_any"]["cell_means"][f"{L}_{c}"] for c in PAYS) for L in L4}
fought = {L: lv[L]["fights_med"] for L in L4}
has = lambda L: lv[L]["fights_med"] and lv[L]["fights_med"] > 0
rows = [
 ("runs", [str(lv[L]["n"]) for L in L4]),
 ("recipients per message", [f1(cu[L]["recipients"]) for L in L4]),
 ("runs with a named agreement (\\%)", [pct(names_any[L]) for L in L4]),
 ("clubs", [f"{med(L, 'K'):.0f}" for L in L4]),
 ("club modularity $Q$ (null)", [f"{f2(mn[L]['Q'])} ({f2(mn[L]['Q_null'])})" for L in L4]),
 ("degree, tie graph", [f1(lv[L]["tie_degree_med"]) for L in L4]),
 ("degree, interaction graph", [f1(mn[L]["mean_degree"]) for L in L4]),
 ("fights per run", [f"{lv[L]['fights_med']:.0f}" for L in L4]),
 ("fought alone (\\%)", [pct(lv[L]["alone_pooled"]) if has(L) else D for L in L4]),
 ("largest mob per round", [D] + [f1(mp[L]["mob"]) for L in ("L2", "L3", "L4")]),
 ("fights on the three richest (\\%; chance)", [D] + [f"{rb[f'{L} Gemma']['observed']:.1f} ({rb[f'{L} Gemma']['chance_reachable']:.1f})" if has(L) else D for L in ("L2", "L3", "L4")]),
 ("beyond lone arithmetic (\\%)", [pct(lv[L]["beyond_pooled"]) if has(L) else D for L in L4]),
 ("  of which joint (\\%)", [pct(lv[L]["joint_pooled"]) if has(L) else D for L in L4]),
 ("rewiring per round", [D, D] + [f"{med(L, 'rw'):.2f}" for L in ("L3", "L4")]),
 ("mean final holding", [f1(lv[L]["mean_final_med"]) for L in L4]),
 ("Gini of final holdings", [f2(lv[L]["gini_med"]) for L in L4]),
]
t2 = ["% Table 2 --- generated by paper_aamas/tables_main.py from saved outputs; do not edit by hand.",
      "\\begin{tabular}{lcccc}", "\\toprule", " & L1 & L2 & L3 & L4 \\\\", "\\midrule"]
t2 += [f"{a} & " + " & ".join(v) + " \\\\" for a, v in rows]
t2 += ["\\bottomrule", "\\end{tabular}"]

ARMS = (("gemma_all", "Gemma"), ("gemma_shared", "Gemma$^{\\ast}$"), ("qwen", "Qwen"), ("silent", "no channel"))
t3 = ["% Table 3 --- generated by paper_aamas/tables_main.py from arms_levels.json; do not edit by hand.",
      "\\begin{tabular}{llccccccccc}", "\\toprule",
      " & arm & $n$ & fights & beyond & joint & names & pair & mean & Gini & empty \\\\", "\\midrule"]
for L in ("L2", "L3", "L4"):
    for i, (k, lab) in enumerate(ARMS):
        v = al["arms"][L][k]
        t3.append(f"{L if i == 0 else ''} & {lab} & {v['n']} & {v['fights_med']:.0f} & "
                  f"{pct(v['beyond_pooled']) if v['fights_med'] else D} & {pct(v['joint_pooled']) if v['fights_med'] else D} & {v['names_mean']:.1f} & "
                  f"{v['pair_runs']:.0f} & {v['mean_final_med']:.0f} & {f2(v['gini_med'])} & {(format(v['emptied'], '.0f') if L == 'L4' else D)} \\\\")
    if L != "L4": t3.append("\\midrule")
t3 += ["\\bottomrule", "\\end{tabular}"]
from _paths import PAPER
out = Path(sys.argv[1]) if len(sys.argv) > 1 else PAPER / "sections"
(out / "tab_levels_main.tex").write_text("\n".join(t2) + "\n")
(out / "tab_arms.tex").write_text("\n".join(t3) + "\n")
print("\n".join(t2)); print("\n".join(t3))
